function create_lvm_volume now working

diff --git a/lxct-create b/lxct-create
--- a/lxct-create
+++ b/lxct-create
@@ -191,20 +191,24 @@ EOF
 		fi
 		LVROOTFS="/dev/$LVM/$NAME"
 		lvdisplay $LVROOTFS > /dev/null 2>&1
-		if [ $? -eq 0 ]; then
-			error "$(basename $0) error: $LVROOTFS already exists in vggroup $LVM" >&2
+		if [ $? -ne 0 ]; then
+			error "error: $LVROOTFS already exists in vggroup $LVM" >&2
 			exit 1
 		fi
 		$LVCREATE -n $NAME --size $SIZE $LVM 2>&1
-		if [ $? -eq 0 ]; then
-			error "$(basename $0) error creating $LVROOTFS in vggroup $LVM, aborted" >&2
+		if [ $? -ne 0 ]; then
+			error "error creating $LVROOTFS in vggroup $LVM, aborted" >&2
 			exit 1
 		fi
 		# volume format
 		if [ -f "$LVROOTFS" ]; then
 			/sbin/mkfs.$FS -L $NAME $LVROOTFS
+			if [ $? -ne 0 ]; then
+				error "error formatting $LVROOTFS with $FS filesystem, aborted" >&2
+				exit 1
+			fi
 		else
-			error "$(basename $0) error: $LVROOTFS not created"
+			error "error: $LVROOTFS not created"
 			exit 1
 		fi
   fi
