testing btrfs sub-volume functionality

diff --git a/lxct-create b/lxct-create
--- a/lxct-create
+++ b/lxct-create
@@ -242,18 +242,23 @@ create_btrfs_volume() {
 	#TODO
 	if [ "$BACKEND_METHOD" = 'btrfs' ]; then
 		# btrfs is installed?
-		BTRFS=`which btrfs`
-		if [ ! -f "$BTRFS" ]; then
+		if [ ! -f `which btrfs` ]; then
 			error "'btrfs' command is missing, run 'apt-get install btrfs-tools'"
 			exit 1
 		fi
 		# is directory a BTRFS volume?
-		btrfs filesystem df $DIR > /dev/null 2>&1
-		if [ $? -eq 0 ]; then
-			error "$DIR is not a BTRFS volume, use DIR for define a BTRFS mount point"
+		result=`btrfs filesystem df $DIR`
+		if [ $? -ne 0 ]; then
+			error "$DIR is not a BTRFS volume, use DIR to define a BTRFS mount point"
 			exit 1
 		fi
-		get_size
+		debug " - creating BTRFS sub-volume $NAME in $DIR"
+		# crear un sub-volumen
+		btrfs subvolume create $DIR/$NAME
+		if [ $? -ne 0 ]; then
+			error "error creating btrfs sub-volume in volume $DIR, aborted" >&2
+			exit 1
+		fi
 		debug "create a sub-volume via btrfs"
 	fi
 }
@@ -592,20 +597,21 @@ main()
 
 	# TODO, ¿pedir confirmación para proceder luego del sumario?
 
-    make_rootfs
-
 	case "$BACKEND_METHOD" in
 	"btrfs")
 		#TODO: no options yet
 		create_btrfs_volume
+		make_rootfs
 		touch_config
 		echo "btrfs" && exit 0;;
 	"dir")
+		make_rootfs
 		# create config-file
 		touch_config
 		;;
 	"lvm")
 		# mount LVM volume
+		make_rootfs
 		create_lvm_volume
 		touch_config
 		;;
