option added: clean cache and activate debug

diff --git a/templates.d/lxc-debian b/templates.d/lxc-debian
--- a/templates.d/lxc-debian
+++ b/templates.d/lxc-debian
@@ -7,6 +7,22 @@
 #
 # debootstrap debian install
 #
+# based on:
+# Daniel Lezcano <daniel.lezcano@free.fr>
+# Authors:
+# Jesus Lara <jesuslarag@phenobarbital.info>
+#
+# This library is free software; you can redistribute it and/or
+# modify it under the terms of the GNU Lesser General Public
+# License as published by the Free Software Foundation; either
+# version 2.1 of the License, or (at your option) any later version.
+# This library is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
+# Lesser General Public License for more details.
+# You should have received a copy of the GNU Lesser General Public
+# License along with this library; if not, write to the Free Software
+# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 
 LAN_INTERFACE='eth0'
 
@@ -36,6 +52,17 @@ download_debian()
     return 0
 }
 
+copy_debian()
+{
+	# make a local copy of the minidebian
+    info "Copying rootfs to $ROOTFS..."
+    cp -apr $CACHE/$SUITE/rootfs-$ARCH/* $ROOTFS/ || return 1
+    if [ $? -ne 0 ]; then
+		error "Failed to copy rootfs"
+        exit 1
+    fi
+}
+
 install_debian() 
 {
 
@@ -46,7 +73,13 @@ install_debian()
             error "Cache repository is busy."
             exit 1
         fi
-
+		
+        # cleaning cache of mini debian
+        if [ "$CLEAN_CACHE" -eq "1" ]; then
+			message "Cache found in $CACHE/$SUITE/rootfs-$ARCH. clearing ..."
+			rm -fR $CACHE/$SUITE/rootfs-$ARCH
+        fi
+        
         # check the mini debian was not already downloaded
         message "Checking cache download in $CACHE/$SUITE/rootfs-$ARCH ... "
         if [ ! -e "$CACHE/$SUITE/rootfs-$ARCH" ]; then
@@ -56,15 +89,9 @@ install_debian()
                 exit 1
             fi
         fi
-
-        # make a local copy of the minidebian
-        info "Copying rootfs to $ROOTFS..."
-        cp -apr $CACHE/$SUITE/rootfs-$ARCH/* $ROOTFS/ || return 1
-        if [ $? -ne 0 ]; then
-            error "Failed to copy rootfs"
-            exit 1
-        fi
-
+        
+        copy_debian
+        
         return 0
 
         ) 200>/var/lock/subsys/lxc
